version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-2:381196861170:task-definition/mvc-thymeleaf-task:2"
        LoadBalancerInfo:
          ContainerName: "mvc-thymeleaf-container"
          ContainerPort: 80