version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:eu-west-1:381196861170:task-definition/demo-task:1"
        LoadBalancerInfo:
          ContainerName: "demo-container"
          ContainerPort: 8080
